app: headless-cms
service: api

provider:
  name: aws
  runtime: nodejs12.x
  stage: local
  region: eu-west-1

layers:
  chrome:
    package:
      artifact: layer/nodejs.zip  

functions:
  hello:
    handler: hello_world/index.handler
    events:
      - http:
          path: /hello
          method: any
    environment:
      ENVIRONMENT: ${env:ENVIRONMENT}
      DYNAMO_HOST: ${env:DYNAMO_HOST}
custom:
  serverless-offline:
    host: 0.0.0.0

plugins:
  - serverless-offline